enum ActionTypeKeys {
  INCREMENT = 'INCREMENT',
  DECREMENT = 'DECREMENT',
  LOGIN='LOGIN',
  LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS',
LOGIN_USER_FAIL='LOGIN_USER_FAIL',
LOGIN_USER='LOGIN',
}

export default ActionTypeKeys;
