enum ActionTypeKeys {
  INCREMENT = 'INCREMENT',
  DECREMENT = 'DECREMENT',
  LOGIN = 'LOGIN',
  LOGINSUCCESS = 'LOGINSUCCESS',
  LOGINFAIL = 'LOGINFAIL',
  LOADING = 'LOADING',
  LOGOUT = 'LOGOUT',
  MENUITEMS ='MENUITEMS',
}

export default ActionTypeKeys;
