enum ActionTypeKeys {
  INCREMENT = 'INCREMENT',
  DECREMENT = 'DECREMENT',
  LOGIN = 'LOGIN',
  LOGINSUCCESS = 'LOGINSUCCESS',
  LOGINFAIL = 'LOGINFAIL',
  LOADING = 'LOADING',
  LOGOUT = 'LOGOUT'
}

export default ActionTypeKeys;
